# Generated by Django 2.2.2 on 2019-08-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_doctor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_teacher',
            new_name='is_patient',
        ),
    ]
