# Generated by Django 2.2.2 on 2019-08-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190810_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
