# Generated by Django 2.2.5 on 2019-10-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191022_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(default='Enter a Valid Blood Group', max_length=10),
        ),
    ]
