# Generated by Django 2.2.2 on 2019-09-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='license_number',
            field=models.CharField(default='Enter Valid License Number', max_length=50),
        ),
    ]
