# Generated by Django 2.2.2 on 2019-08-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_auto_20190818_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='image',
            field=models.ImageField(blank=True, upload_to='documents/'),
        ),
    ]
