# Generated by Django 2.2.2 on 2019-08-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_auto_20190824_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='image',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
