# Generated by Django 2.2.2 on 2019-09-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0005_auto_20190831_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='record',
            field=models.CharField(max_length=100),
        ),
    ]
