# Generated by Django 2.2.2 on 2019-09-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0006_auto_20190901_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='record',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
