# Generated by Django 2.2.3 on 2019-09-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0007_auto_20190901_1649'),
        ('prescription', '0006_prescriptions_text'),
    ]

    operations = [
    ]
