# Generated by Django 2.2.5 on 2019-10-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0009_auto_20190904_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptions',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
