# Generated by Django 2.2.5 on 2019-10-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0011_xray'),
    ]

    operations = [
        migrations.AddField(
            model_name='xray',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
