# Generated by Django 2.2.5 on 2019-10-21 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0013_xray_predictions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XRay',
        ),
    ]
