# Generated by Django 2.2.5 on 2019-10-21 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescription', '0014_delete_xray'),
    ]

    operations = [
        migrations.CreateModel(
            name='XRay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='xrays/')),
                ('name', models.CharField(default='name', max_length=100)),
                ('predictions', models.TextField(default='')),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
